name = "cfp"
account_id = "db6c4c6879c872694350fefa5b59091a"
workers_dev = true
compatibility_date = "2025-12-08"

[assets]
directory = "./dist"

[[kv_namespaces]]
binding = "wdns"
id = "43036a794f2545e792342cd1774e8f3f"
